apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-config
  namespace: payment-system
data:
  DB_USER: postgres
  REDIS_HOST: "192.168.1.16"
  REDIS_PORT: "6379"
  KAFKA_BOOTSTRAP_SERVERS: "192.168.1.16:9092"
  SPRING_PROFILES_ACTIVE: kubernetes
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://192.168.1.16:8761/eureka/"
