apiVersion: v1
kind: Secret
metadata:
  name: payment-secrets
  namespace: payment-system
type: Opaque
stringData:
  DB_PASSWORD: postgres
  JWT_ACCESS_SECRET: super-secret-key-at-least-32-chars-long!!
